2023-05-15 22:45:14,258 INFO    StreamThr :18597 [internal.py:wandb_internal():89] W&B internal server running at pid: 18597, started at: 2023-05-15 22:45:14.257901
2023-05-15 22:45:14,261 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status
2023-05-15 22:45:14,264 INFO    WriterThread:18597 [datastore.py:open_for_write():85] open: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/run-f4cumxg5.wandb
2023-05-15 22:45:14,265 DEBUG   SenderThread:18597 [sender.py:send():375] send: header
2023-05-15 22:45:14,355 DEBUG   SenderThread:18597 [sender.py:send():375] send: run
2023-05-15 22:45:14,879 INFO    SenderThread:18597 [dir_watcher.py:__init__():219] watching files in: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/files
2023-05-15 22:45:14,879 INFO    SenderThread:18597 [sender.py:_start_run_threads():1127] run started: f4cumxg5 with start time 1684190714.259368
2023-05-15 22:45:14,879 DEBUG   SenderThread:18597 [sender.py:send_request():402] send_request: summary_record
2023-05-15 22:45:14,879 INFO    SenderThread:18597 [sender.py:_save_file():1378] saving file wandb-summary.json with policy end
2023-05-15 22:45:14,882 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: check_version
2023-05-15 22:45:14,882 DEBUG   SenderThread:18597 [sender.py:send_request():402] send_request: check_version
2023-05-15 22:45:14,962 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: run_start
2023-05-15 22:45:14,965 DEBUG   HandlerThread:18597 [system_info.py:__init__():31] System info init
2023-05-15 22:45:14,966 DEBUG   HandlerThread:18597 [system_info.py:__init__():46] System info init done
2023-05-15 22:45:14,966 INFO    HandlerThread:18597 [system_monitor.py:start():181] Starting system monitor
2023-05-15 22:45:14,966 INFO    SystemMonitor:18597 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-05-15 22:45:14,966 INFO    HandlerThread:18597 [system_monitor.py:probe():201] Collecting system info
2023-05-15 22:45:14,967 INFO    SystemMonitor:18597 [interfaces.py:start():190] Started cpu monitoring
2023-05-15 22:45:14,967 INFO    SystemMonitor:18597 [interfaces.py:start():190] Started disk monitoring
2023-05-15 22:45:14,969 INFO    SystemMonitor:18597 [interfaces.py:start():190] Started gpu monitoring
2023-05-15 22:45:14,970 INFO    SystemMonitor:18597 [interfaces.py:start():190] Started memory monitoring
2023-05-15 22:45:14,971 INFO    SystemMonitor:18597 [interfaces.py:start():190] Started network monitoring
2023-05-15 22:45:14,979 DEBUG   HandlerThread:18597 [system_info.py:probe():195] Probing system
2023-05-15 22:45:14,987 DEBUG   HandlerThread:18597 [system_info.py:_probe_git():180] Probing git
2023-05-15 22:45:15,004 DEBUG   HandlerThread:18597 [system_info.py:_probe_git():188] Probing git done
2023-05-15 22:45:15,004 DEBUG   HandlerThread:18597 [system_info.py:probe():240] Probing system done
2023-05-15 22:45:15,004 DEBUG   HandlerThread:18597 [system_monitor.py:probe():210] {'os': 'Linux-4.4.0-59-generic-x86_64-with-debian-buster-sid', 'python': '3.7.0', 'heartbeatAt': '2023-05-15T22:45:14.979643', 'startedAt': '2023-05-15T22:45:14.247522', 'docker': None, 'cuda': None, 'args': ('--model', 'tood_swinv2-t-p4-w16_fpn_resize_coco_cosinelr', '--folder', 'tood', '--max_epoch', '36'), 'state': 'running', 'program': 'main.py', 'codePath': 'UniverseNet/tools/main.py', 'git': {'remote': 'https://github.com/boostcampaitech5/level2_objectdetection-cv-11.git', 'commit': '71a591a8c62b0f7ab9076a5e523548b55cc4278e'}, 'email': 'hjhhijk@gmail.com', 'root': '/opt/ml/level2_objectdetection-cv-11', 'host': '31250d40d265', 'username': 'root', 'executable': '/opt/conda/envs/project2/bin/python3', 'cpu_count': 8, 'cpu_count_logical': 8, 'cpu_freq': {'current': 2200.02, 'min': 0.0, 'max': 0.0}, 'cpu_freq_per_core': [{'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}, {'current': 2200.02, 'min': 0.0, 'max': 0.0}], 'disk': {'total': 98.30496215820312, 'used': 76.13971328735352}, 'gpu': 'Tesla V100-PCIE-32GB', 'gpu_count': 1, 'gpu_devices': [{'name': 'Tesla V100-PCIE-32GB', 'memory_total': 34089730048}], 'memory': {'total': 88.50595092773438}}
2023-05-15 22:45:15,004 INFO    HandlerThread:18597 [system_monitor.py:probe():211] Finished collecting system info
2023-05-15 22:45:15,004 INFO    HandlerThread:18597 [system_monitor.py:probe():214] Publishing system info
2023-05-15 22:45:15,004 DEBUG   HandlerThread:18597 [system_info.py:_save_pip():52] Saving list of pip packages installed into the current environment
2023-05-15 22:45:15,005 DEBUG   HandlerThread:18597 [system_info.py:_save_pip():67] Saving pip packages done
2023-05-15 22:45:15,005 DEBUG   HandlerThread:18597 [system_info.py:_save_conda():75] Saving list of conda packages installed into the current environment
2023-05-15 22:45:15,881 INFO    Thread-12 :18597 [dir_watcher.py:_on_file_created():278] file/dir created: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/files/conda-environment.yaml
2023-05-15 22:45:15,881 INFO    Thread-12 :18597 [dir_watcher.py:_on_file_created():278] file/dir created: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/files/requirements.txt
2023-05-15 22:45:15,882 INFO    Thread-12 :18597 [dir_watcher.py:_on_file_created():278] file/dir created: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/files/wandb-summary.json
2023-05-15 22:45:23,664 DEBUG   HandlerThread:18597 [system_info.py:_save_conda():86] Saving conda packages done
2023-05-15 22:45:23,665 INFO    HandlerThread:18597 [system_monitor.py:probe():216] Finished publishing system info
2023-05-15 22:45:23,671 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status_report
2023-05-15 22:45:23,671 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:45:23,672 DEBUG   SenderThread:18597 [sender.py:send():375] send: files
2023-05-15 22:45:23,672 INFO    SenderThread:18597 [sender.py:_save_file():1378] saving file wandb-metadata.json with policy now
2023-05-15 22:45:23,678 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: stop_status
2023-05-15 22:45:23,678 DEBUG   SenderThread:18597 [sender.py:send_request():402] send_request: stop_status
2023-05-15 22:45:23,867 ERROR   Thread-11 :18597 [step_upload.py:_handle_event():197] Failed to upload file: /tmp/tmpu7fua243wandb/l67yo5jo-wandb-metadata.json
Traceback (most recent call last):
  File "/opt/conda/envs/project2/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 284, in run_and_notify
    self._do_upload_sync(event)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/filesync/step_upload.py", line 330, in _do_upload_sync
    job.run()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 61, in run
    self.push()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/filesync/upload_job.py", line 112, in push
    _, upload_headers, result = self._api.upload_urls(project, [self.save_name])
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/apis/normalize.py", line 73, in wrapper
    raise err
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1866, in upload_urls
    raise CommError(f"Run does not exist {entity}/{project}/{run_id}.")
wandb.errors.CommError: Run does not exist aivengers_v2/trash_detection V1 (model selection)/f4cumxg5.
2023-05-15 22:45:23,885 INFO    Thread-12 :18597 [dir_watcher.py:_on_file_modified():295] file/dir modified: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/files/conda-environment.yaml
2023-05-15 22:45:23,885 INFO    Thread-12 :18597 [dir_watcher.py:_on_file_created():278] file/dir created: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/files/wandb-metadata.json
2023-05-15 22:45:23,886 DEBUG   SenderThread:18597 [sender.py:send():375] send: telemetry
2023-05-15 22:45:25,887 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status_report
2023-05-15 22:45:30,887 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status_report
2023-05-15 22:45:35,888 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status_report
2023-05-15 22:45:38,678 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: stop_status
2023-05-15 22:45:38,679 DEBUG   SenderThread:18597 [sender.py:send_request():402] send_request: stop_status
2023-05-15 22:45:41,879 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status_report
2023-05-15 22:45:46,885 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: status_report
2023-05-15 22:45:47,093 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:45:47,093 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:45:48,374 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:45:48,374 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:45:50,923 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:45:50,924 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:45:50,924 INFO    SenderThread:18597 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql
2023-05-15 22:45:53,678 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: stop_status
2023-05-15 22:45:55,691 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:45:55,691 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:45:58,679 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:03,680 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:05,061 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:46:05,061 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:46:08,681 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:13,682 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:14,971 DEBUG   SystemMonitor:18597 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-05-15 22:46:18,683 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:23,684 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:24,276 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:46:24,276 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:46:26,883 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: partial_history
2023-05-15 22:46:28,689 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:33,690 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:38,691 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:43,691 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:48,692 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:53,693 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:46:58,695 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:01,803 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:47:01,803 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:47:03,698 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:08,704 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:13,705 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:18,706 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:23,707 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:27,203 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: partial_history
2023-05-15 22:47:28,707 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:33,708 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:38,709 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:43,727 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:48,728 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:53,729 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:47:58,729 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:48:03,730 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:48:08,731 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:48:12,824 ERROR   SenderThread:18597 [internal_api.py:execute():288] 409 response executing GraphQL.
2023-05-15 22:48:12,824 ERROR   SenderThread:18597 [internal_api.py:execute():289] {"errors":[{"message":"run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name","path":["upsertBucket"]}],"data":{"upsertBucket":null}}
2023-05-15 22:48:12,978 INFO    WriterThread:18597 [datastore.py:close():298] close: /opt/ml/level2_objectdetection-cv-11/UniverseNet/tools/wandb/run-20230515_224514-f4cumxg5/run-f4cumxg5.wandb
2023-05-15 22:48:13,732 DEBUG   HandlerThread:18597 [handler.py:handle_request():144] handle_request: keepalive
2023-05-15 22:48:13,733 INFO    HandlerThread:18597 [handler.py:finish():845] shutting down handler
2023-05-15 22:48:13,733 INFO    HandlerThread:18597 [system_monitor.py:finish():190] Stopping system monitor
2023-05-15 22:48:13,733 DEBUG   SystemMonitor:18597 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-05-15 22:48:13,734 DEBUG   SystemMonitor:18597 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-05-15 22:48:13,735 INFO    HandlerThread:18597 [interfaces.py:finish():202] Joined cpu monitor
2023-05-15 22:48:13,735 INFO    HandlerThread:18597 [interfaces.py:finish():202] Joined disk monitor
2023-05-15 22:48:13,744 INFO    HandlerThread:18597 [interfaces.py:finish():202] Joined gpu monitor
2023-05-15 22:48:13,744 INFO    HandlerThread:18597 [interfaces.py:finish():202] Joined memory monitor
2023-05-15 22:48:13,745 INFO    HandlerThread:18597 [interfaces.py:finish():202] Joined network monitor
2023-05-15 22:48:13,745 ERROR   StreamThr :18597 [internal.py:wandb_internal():174] Thread SenderThread:
Traceback (most recent call last):
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/apis/normalize.py", line 41, in wrapper
    return func(*args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1694, in upsert_run
    **kwargs,
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 260, in gql
    **kwargs,
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 285, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/lib/gql_request.py", line 56, in execute
    request.raise_for_status()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 49, in run
    self._run()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal_util.py", line 93, in _run
    self._debounce()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/internal.py", line 334, in _debounce
    self._sm.debounce()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 551, in debounce
    self._maybe_update_config(always=final)
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 528, in _maybe_update_config
    self._debounce_config()
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/sdk/internal/sender.py", line 558, in _debounce_config
    name=self._run.run_id, config=config_value_dict, **self._api_settings  # type: ignore
  File "/opt/conda/envs/project2/lib/python3.7/site-packages/wandb/apis/normalize.py", line 51, in wrapper
    raise CommError(message, error)
wandb.errors.CommError: run aivengers_v2/trash_detection V1 (model selection)/f4cumxg5 was previously created and deleted; try a new run name (Error 409: Conflict)
